FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

COPY requirements-monolith.txt .
RUN pip install --no-cache-dir -r requirements-monolith.txt

COPY app ./app

RUN mkdir -p /app/data

CMD ["python", "-m", "app.main"]
